spring.application.name=microservicesKafka
server.port=8081

eureka.client.restclient.enabled=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=defaultGroup
spring.kafka.consumer.auto-offset-reset=earliest